# Generated by Django 4.0.8 on 2024-07-11 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icd_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nidn', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='patientdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(help_text='Nomor Induk Kependudukan / Nomor Rekam Medis', max_length=20, unique=True, verbose_name='ID Number')),
                ('name', models.CharField(help_text='Nama Pasien', max_length=100, verbose_name="Patient's Name")),
                ('phone_number', models.CharField(help_text='Nomor Telfon', max_length=15, verbose_name='Phone Number')),
                ('date_of_birth', models.DateField(help_text='Tanggal Lahir', verbose_name='Date Of Birth')),
                ('ethnic_group', models.CharField(help_text='Suku Bangsa', max_length=50, verbose_name='Ethnic Group')),
                ('chief_complaint', models.TextField(help_text='Keluhan Utama', verbose_name='Chief Complaint')),
                ('health_insurance', models.CharField(help_text='Asuransi Kesehatan', max_length=100, verbose_name='Health Insurance')),
                ('address', models.CharField(help_text='Alamat', max_length=255, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='SurveySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Survey', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_record', models.CharField(help_text='Nomor Rekam Medis', max_length=20, verbose_name='Medical Record Number')),
                ('date_of_treatment', models.DateField(help_text='Tanggal Pengobatan', verbose_name='Date of Treatment')),
                ('service_unit', models.CharField(help_text='Unit Layanan', max_length=100, verbose_name='Service Unit')),
                ('stadium', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stadium')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Grade')),
                ('tumor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tumor (T)')),
                ('nodes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nodes (N)')),
                ('metastasis', models.CharField(blank=True, max_length=50, null=True, verbose_name='Metastasis (M)')),
                ('bone_scan', models.CharField(blank=True, max_length=100, verbose_name='Bone Scan')),
                ('pet_scan', models.CharField(blank=True, max_length=100, verbose_name='Pet Scan')),
                ('psma_pet_ct', models.CharField(blank=True, max_length=100, verbose_name='PSMA PET/CT')),
                ('choline_pet_ct', models.CharField(blank=True, max_length=100, verbose_name='Choline PET/CT')),
                ('fluoride_pet', models.CharField(blank=True, max_length=100, verbose_name='Fluoride PET')),
                ('treatment', models.TextField(blank=True, verbose_name='Tindakan/Terapi')),
                ('incontinence', models.BooleanField(default=False)),
                ('pad_usage', models.CharField(blank=True, max_length=100, null=True)),
                ('erectile_dysfunction', models.BooleanField(default=False)),
                ('side_effects', models.TextField(blank=True, null=True)),
                ('subjective', models.TextField(blank=True, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('assessment', models.TextField(blank=True, null=True)),
                ('plan', models.TextField(blank=True, null=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prostate.diagnosis')),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prostate.doctor')),
                ('hospital_name', models.ForeignKey(help_text='Nama Rumah Sakit', on_delete=django.db.models.deletion.CASCADE, to='prostate.hospital', verbose_name='Hospital Name')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prostate.patientdata')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='prostate.surveyset')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('question_type', models.CharField(choices=[('text', 'Text Input'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox'), ('textarea', 'Text Area')], max_length=20)),
                ('survey_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='prostate.surveyset')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='prostate.surveyquestion')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prostate.surveyquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='prostate.surveyresponse')),
            ],
        ),
    ]
